
CC=g++
CFLAGS= 

INCLUDE = 
LIBS	= -L. -lddfs
RM	= /bin/rm

# Objs are all the sources, with .cpp replaced by .o

all : $(ECHO)
	$(CC) $(CFLAGS) $(INCLUDE) $(LIBS) -o test1 test1.cpp
	

clean:
	$(RM) -f $(OBJS)
